/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JLabel;
import ventasdao.controladores.ClienteControlador;
import ventasdao.controladores.ControladorFactura;
import ventasdao.controladores.ControladorProducto;
import ventasdao.objetos.Cliente;
import ventasdao.objetos.Factura;
import ventasdao.objetos.Producto;
import ventasdao.ui.grilla.GrillaFactura;
import ventasdao.ui.grilla.GrillaProductoFactura;

/**
 *
 * @author Arguello Leonel
 */
public class AbmFactura extends javax.swing.JInternalFrame {

    private Factura factura;
    private GrillaFactura grillafactura;
    private ControladorFactura controladorFactura;
    private ClienteControlador clienteControlador;
    private ControladorProducto productoControlador;
    private DefaultComboBoxModel modelcombo;
    private DefaultComboBoxModel modelcombo2;
            Float preciotemporal= 0f;
            Float cantidadtemporal=0f;
            ArrayList<Producto> productosobtenidos;




    /**
     * Creates new form AbmFactura
     * @throws java.lang.Exception
     */
    public AbmFactura() throws Exception  {
        initComponents();
        controladorFactura= new ControladorFactura();
        clienteControlador= new ClienteControlador();
        productoControlador= new ControladorProducto();
             try {
            grillafactura= new GrillaFactura(controladorFactura.listar());
            tablefacturas1.setModel(grillafactura);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        try {
            ArrayList<Cliente> clientes = clienteControlador.listar();
                    modelcombo= new DefaultComboBoxModel(clientes.toArray());
                    CB_Cliente.setModel(modelcombo);
           
        } catch (Exception ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
             ArrayList<Producto> productos = productoControlador.listar();
                    modelcombo2= new DefaultComboBoxModel(productos.toArray());
                    CB_Producto.setModel(modelcombo2);
                    
         } catch (Exception ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
            /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_Cliente = new javax.swing.JComboBox<>();
        DateFactura = new com.toedter.calendar.JDateChooser();
        CB_Producto = new javax.swing.JComboBox<>();
        JObservacion = new javax.swing.JTextField();
        B_Producto = new javax.swing.JButton();
        JCantidad = new javax.swing.JTextField();
        CB_Pago = new javax.swing.JComboBox<>();
        lTotal = new javax.swing.JLabel();
        lTotal1 = new javax.swing.JLabel();
        lTotal2 = new javax.swing.JLabel();
        lTotal3 = new javax.swing.JLabel();
        lTotal4 = new javax.swing.JLabel();
        lTotal5 = new javax.swing.JLabel();
        lTotal6 = new javax.swing.JLabel();
        lTotal7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablefacturas1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableproductos = new javax.swing.JTable();
        JTotal = new javax.swing.JTextField();

        CB_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CB_Producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        B_Producto.setText("Añadir Producto");
        B_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_ProductoActionPerformed(evt);
            }
        });

        JCantidad.setText("1");

        CB_Pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta de Credito", "Tarjeta de Debito", "Efectivo", "Mercadopago" }));

        lTotal1.setText("Fecha");

        lTotal2.setText("Cliente");

        lTotal3.setText("Producto");

        lTotal4.setText("Cantidad");

        lTotal5.setText("Observacion");

        lTotal6.setText("Total");

        lTotal7.setText("Forma de pago");

        jButton1.setText("Generar Factura ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tablefacturas1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablefacturas1);

        tableproductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Producto", "Cantidad", "Precio"
            }
        ));
        jScrollPane3.setViewportView(tableproductos);

        JTotal.setText("$");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(315, 315, 315)
                .addComponent(lTotal)
                .addContainerGap(465, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTotal1)
                            .addComponent(lTotal2)
                            .addComponent(lTotal3)
                            .addComponent(lTotal4)
                            .addComponent(lTotal5)
                            .addComponent(lTotal6)
                            .addComponent(lTotal7))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_Producto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_Cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JObservacion)
                            .addComponent(JCantidad)
                            .addComponent(CB_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(DateFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lTotal1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(CB_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lTotal2))
                                        .addGap(18, 18, 18)
                                        .addComponent(CB_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lTotal3))
                                .addGap(18, 18, 18)
                                .addComponent(JCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lTotal4))
                        .addGap(12, 12, 12)
                        .addComponent(B_Producto))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lTotal5)
                                .addGap(45, 45, 45))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(JObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lTotal7)
                                    .addComponent(CB_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lTotal6)
                            .addComponent(JTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(lTotal)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_ProductoActionPerformed
        
        Producto producto= new Producto();
        producto.setNombre(CB_Producto.getSelectedItem().toString());
        
        Producto productoobtenido= new Producto();
        try {
            productoobtenido = productoControlador.objeto(producto.getNombre());
        } catch (Exception ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        Float cantidadproducto= Float.parseFloat(JCantidad.getText());
        float precioproducto= Float.parseFloat(JCantidad.getText()) * productoobtenido.getPrecio();
                preciotemporal= preciotemporal + precioproducto;
                cantidadtemporal= cantidadtemporal + cantidadproducto;
                       JTotal.setText(preciotemporal.toString());

    }//GEN-LAST:event_B_ProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Factura factura = new Factura();
        factura.setFecha(DateFactura.getDate());
        factura.setId_cliente((Integer) CB_Cliente.getSelectedItem());
        String temporal= cantidadtemporal.toString();
        factura.setCantidad_producto(Integer.parseInt(temporal));
        factura.setObservacion(JObservacion.getText());
        factura.setForma_pago((String) CB_Pago.getSelectedItem());
        factura.setTotal(Float.parseFloat(JTotal.getText()));
        
        try {
            controladorFactura.crear(factura);
             //limpiarCampos();
        
        } catch (Exception ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        try {
            grillafactura= new GrillaFactura(controladorFactura.listar());
            tablefacturas1.setModel(grillafactura);
        } catch (Exception ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Producto;
    private javax.swing.JComboBox<String> CB_Cliente;
    private javax.swing.JComboBox<String> CB_Pago;
    private javax.swing.JComboBox<String> CB_Producto;
    private com.toedter.calendar.JDateChooser DateFactura;
    private javax.swing.JTextField JCantidad;
    private javax.swing.JTextField JObservacion;
    private javax.swing.JTextField JTotal;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel lTotal1;
    private javax.swing.JLabel lTotal2;
    private javax.swing.JLabel lTotal3;
    private javax.swing.JLabel lTotal4;
    private javax.swing.JLabel lTotal5;
    private javax.swing.JLabel lTotal6;
    private javax.swing.JLabel lTotal7;
    private javax.swing.JTable tablefacturas1;
    private javax.swing.JTable tableproductos;
    // End of variables declaration//GEN-END:variables
}
