/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasdao.ui.abm;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import ventasdao.controladores.ClienteControlador;
import ventasdao.controladores.ControladorFactura;
import ventasdao.controladores.ControladorProducto;
import ventasdao.objetos.Cliente;
import ventasdao.objetos.Factura;
import ventasdao.objetos.Producto;
import ventasdao.ui.grilla.GrillaFactura;

/**
 *
 * @author Arguello Leonel
 */
public class AbmFactura extends javax.swing.JInternalFrame {

    private Factura factura;
    private GrillaFactura grillafactura;
    private ControladorFactura controladorFactura;
    private ClienteControlador clienteControlador;
    private ControladorProducto productoControlador;
    private DefaultComboBoxModel modelcombo;
    private DefaultComboBoxModel modelcombo2;



    /**
     * Creates new form AbmFactura
     * @throws java.lang.Exception
     */
    public AbmFactura() throws Exception  {
        initComponents();
        controladorFactura= new ControladorFactura();
        clienteControlador= new ClienteControlador();
     
             try {
            grillafactura= new GrillaFactura(controladorFactura.listar());
            tablefacturas.setModel(grillafactura);
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        try {
            ArrayList<Cliente> clientes = clienteControlador.listar();
                    modelcombo= new DefaultComboBoxModel(clientes.toArray());
                    CB_Cliente.setModel(modelcombo);
           
        } catch (Exception ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
             try {
            ArrayList<Producto> productos = productoControlador.listar();
                    modelcombo2= new DefaultComboBoxModel(productos.toArray());
                    CB_Producto.setModel(modelcombo2);
                    

        } catch (Exception ex) {
            Logger.getLogger(AbmFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    
         
    }
            /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CB_Cliente = new javax.swing.JComboBox<>();
        DateFactura = new com.toedter.calendar.JDateChooser();
        CB_Producto = new javax.swing.JComboBox<>();
        JObservacion = new javax.swing.JTextField();
        B_Producto = new javax.swing.JButton();
        JCantidad1 = new javax.swing.JTextField();
        CB_Pago = new javax.swing.JComboBox<>();
        lTotal = new javax.swing.JLabel();
        lTotal1 = new javax.swing.JLabel();
        lTotal2 = new javax.swing.JLabel();
        lTotal3 = new javax.swing.JLabel();
        lTotal4 = new javax.swing.JLabel();
        lTotal5 = new javax.swing.JLabel();
        lTotal6 = new javax.swing.JLabel();
        lTotal7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablefacturas = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        CB_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        CB_Producto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        CB_Producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CB_ProductoActionPerformed(evt);
            }
        });

        B_Producto.setText("Añadir Producto");

        CB_Pago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tarjeta de Credito", "Tarjeta de Debito", "Efectivo", "Mercadopago" }));

        lTotal1.setText("Fecha");

        lTotal2.setText("Cliente");

        lTotal3.setText("Producto");

        lTotal4.setText("Cantidad");

        lTotal5.setText("Observacion");

        lTotal6.setText("Total");

        lTotal7.setText("Forma de pago");

        tablefacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablefacturas);

        jButton1.setText("Generar Factura ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(315, 315, 315)
                        .addComponent(lTotal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lTotal1)
                            .addComponent(lTotal2)
                            .addComponent(lTotal3)
                            .addComponent(lTotal4)
                            .addComponent(lTotal5)
                            .addComponent(lTotal6)
                            .addComponent(lTotal7))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B_Producto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_Producto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CB_Cliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DateFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JObservacion)
                            .addComponent(JCantidad1)
                            .addComponent(CB_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(DateFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lTotal1))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(CB_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lTotal2))
                                        .addGap(18, 18, 18)
                                        .addComponent(CB_Producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lTotal3))
                                .addGap(18, 18, 18)
                                .addComponent(JCantidad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lTotal4))
                        .addGap(12, 12, 12)
                        .addComponent(B_Producto)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(JObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lTotal5))
                                .addGap(18, 18, 18)
                                .addComponent(CB_Pago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lTotal7))
                        .addGap(18, 18, 18)
                        .addComponent(lTotal6)
                        .addGap(12, 12, 12)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 143, Short.MAX_VALUE)
                        .addComponent(lTotal))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CB_ProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CB_ProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CB_ProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_Producto;
    private javax.swing.JComboBox<String> CB_Cliente;
    private javax.swing.JComboBox<String> CB_Pago;
    private javax.swing.JComboBox<String> CB_Producto;
    private com.toedter.calendar.JDateChooser DateFactura;
    private javax.swing.JTextField JCantidad1;
    private javax.swing.JTextField JObservacion;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTotal;
    private javax.swing.JLabel lTotal1;
    private javax.swing.JLabel lTotal2;
    private javax.swing.JLabel lTotal3;
    private javax.swing.JLabel lTotal4;
    private javax.swing.JLabel lTotal5;
    private javax.swing.JLabel lTotal6;
    private javax.swing.JLabel lTotal7;
    private javax.swing.JTable tablefacturas;
    // End of variables declaration//GEN-END:variables
}
